-- ==========================================
-- IDBI SMART LENDING COPILOT - BIGQUERY DDL
-- Enterprise Schema for AI Lead Intelligence & Repayment Engine
-- ==========================================

CREATE SCHEMA IF NOT EXISTS `idbi_lending_analytics`
OPTIONS(location="asia-south1"); -- Mumbai region for compliance with local data hosting regulations

-- Table 1: Raw Customer Profile (Synched from IDBI Core Banking / CRMnext)
CREATE TABLE IF NOT EXISTS `idbi_lending_analytics.customer_profile` (
  customer_id STRING OPTIONS(description="Unique IDBI Customer Reference"),
  cif_id STRING,
  first_name STRING,
  last_name STRING,
  email STRING,
  mobile_number STRING,
  age INT64,
  occupation_type STRING, -- SALARIED, SELF_EMPLOYED, PROFESSIONAL, BUSINESS
  geo_location STRING,
  salary_account_flag BOOLEAN,
  existing_relationship_months INT64,
  credit_score_cibil INT64,
  created_at TIMESTAMP
);

-- Table 2: GPU-Engineered Transaction Aggregates (Output of NVIDIA cuDF Feature Pipeline)
CREATE TABLE IF NOT EXISTS `idbi_lending_analytics.transaction_features` (
  customer_id STRING,
  period_month DATE,
  verified_salary_credits NUMERIC,
  business_inflows NUMERIC,
  rental_inflows NUMERIC,
  other_deposits NUMERIC,
  existing_emi_outflow NUMERIC,
  utility_bill_payments NUMERIC,
  lifestyle_outflows NUMERIC,
  investment_sip_outflows NUMERIC,
  cash_withdrawals NUMERIC,
  cheque_bounces_count INT64,
  upi_inbound_count INT64,
  upi_outbound_count INT64,
  credit_card_payment_sum NUMERIC,
  credit_card_limit_utilization FLOAT64,
  last_updated_at TIMESTAMP
);

-- Table 3: Lead Intelligence Scores (Generated by Vertex AI & Repayment Engine)
CREATE TABLE IF NOT EXISTS `idbi_lending_analytics.lead_scores` (
  lead_id STRING,
  customer_id STRING,
  lead_score FLOAT64,               -- Overall conversion probability (0-100)
  income_confidence_score FLOAT64,  -- Confidence score of declared income (0-100)
  repayment_capacity_score FLOAT64, -- Liquidity health (0-100)
  intent_score FLOAT64,             -- Digital engagement signal (0-100)
  urgency_score FLOAT64,            -- Active search trigger (0-100)
  loan_affinity_type STRING,        -- PERSONAL_LOAN, HOME_LOAN, LAP, AUTO_LOAN, BALANCE_TRANSFER
  estimated_monthly_income NUMERIC,
  disposable_income NUMERIC,
  max_safe_emi NUMERIC,
  eligible_loan_range_min NUMERIC,
  eligible_loan_range_max NUMERIC,
  debt_to_income_ratio FLOAT64,
  risk_rating STRING,               -- LOW, MEDIUM, HIGH
  explainability_text STRING,       -- Text generated for compliance and audits
  computed_at TIMESTAMP
);

-- Table 4: Automated Omnichannel Campaigns & Follow-up Journeys
CREATE TABLE IF NOT EXISTS `idbi_lending_analytics.campaign_activity` (
  campaign_id STRING,
  lead_id STRING,
  channel STRING,                -- WHATSAPP, SMS, EMAIL, IVR, VOICE_BOT
  delivery_status STRING,        -- SENT, DELIVERED, READ, CLICKED, FAILED
  journey_stage STRING,          -- INITIAL_OFFER, REMINDER_D1, REMINDER_D3, EXPIRED
  sent_timestamp TIMESTAMP,
  response_delay_hours INT64,
  customer_response STRING       -- Accepted, Rejected, EMI_Calculator, Talk_To_Advisor, No_Response
);
